
IMAGES: dict[str, str] = {
    "Жим штанги лёжа": "barbell-bench-press---medium-grip",
    "Жим гантелей лёжа": "dumbbell-bench-press",
    "Жим гантелей на наклонной скамье": "incline-dumbbell-press",
    "Отжимания": "pushups",
    "Отжимания на брусьях": "dips---chest-version",
    "Разведение гантелей лёжа": "dumbbell-flyes",
    "Подтягивания": "pullups",
    "Тяга штанги в наклоне": "bent-over-barbell-row",
    "Тяга верхнего блока": "wide-grip-lat-pulldown",
    "Тяга нижнего блока": "seated-cable-rows",
    "Тяга гантели одной рукой": "one-arm-dumbbell-row",
    "Становая тяга": "barbell-deadlift",
    "Гиперэкстензия": "hyperextensions-back-extensions",
    "Приседания со штангой": "barbell-squat",
    "Жим ногами": "leg-press",
    "Румынская тяга": "romanian-deadlift",
    "Выпады с гантелями": "dumbbell-lunges",
    "Болгарские сплит-приседания": "split-squat-with-dumbbells",
    "Кубковые приседания": "goblet-squat",
    "Сгибание ног лёжа": "lying-leg-curls",
    "Разгибание ног": "leg-extensions",
    "Подъём на носки стоя": "standing-calf-raises",
    "Ягодичный мостик": "butt-lift-bridge",
    "Жим штанги стоя": "standing-military-press",
    "Жим гантелей сидя": "dumbbell-shoulder-press",
    "Махи гантелей в стороны": "side-lateral-raise",
    "Разведение гантелей в наклоне": "seated-bent-over-rear-delt-raise",
    "Тяга к лицу (face pull)": "face-pull",
    "Подъём штанги на бицепс": "barbell-curl",
    "Подъём гантелей на бицепс": "dumbbell-bicep-curl",
    "Молотковые сгибания": "hammer-curls",
    "Французский жим": "ez-bar-skullcrusher",
    "Разгибание рук на блоке": "triceps-pushdown",
    "Скручивания": "crunches",
    "Планка (секунды)": "plank",
    "Подъём ног в висе": "hanging-leg-raise",
    "Жим штанги на наклонной скамье": "barbell-incline-bench-press---medium-grip",
    "Жим в тренажёре на грудь": "leverage-chest-press",
    "Сведение рук в кроссовере": "flat-bench-cable-flyes",
    "Пуловер с гантелью": "bent-arm-dumbbell-pullover",
    "Тяга Т-грифа": "t-bar-row-with-handle",
    "Тяга в рычажном тренажёре": "leverage-iso-row",
    "Подтягивания обратным хватом": "chin-up",
    "Пуловер на блоке прямыми руками": "straight-arm-pulldown",
    "Шраги с гантелями": "dumbbell-shrug",
    "Фронтальные приседания": "front-squat-clean-grip",
    "Гакк-приседания": "hack-squat",
    "Сумо-приседания": "plie-dumbbell-squat",
    "Ягодичный мостик со штангой": "barbell-glute-bridge",
    "Выпады в ходьбе": "bodyweight-walking-lunge",
    "Зашагивания на платформу": "dumbbell-step-ups",
    "Сгибание ног сидя": "seated-leg-curl",
    "Подъём на носки сидя": "seated-calf-raise",
    "Приседания с собственным весом": "bodyweight-squat",
    "Жим Арнольда": "arnold-dumbbell-press",
    "Шраги со штангой": "barbell-shrug",
    "Обратные разведения в тренажёре": "reverse-flyes",
    "Сгибания на скамье Скотта": "preacher-curl",
    "Концентрированные сгибания": "concentration-curls",
    "Жим штанги узким хватом": "close-grip-barbell-bench-press",
    "Отжимания от скамьи": "bench-dips",
    "Разгибание гантели из-за головы": "standing-dumbbell-triceps-extension",
    "Сгибание рук в кроссовере": "lying-cable-curl",
    "Подъём ног лёжа": "flat-bench-lying-leg-raise",
    "Скручивания на блоке": "cable-crunch",
    "Русский твист": "russian-twist",
    "Скалолаз (секунды)": "mountain-climbers",
    "Велотренажёр (минуты)": "recumbent-bike",
    "Эллипс (минуты)": "elliptical-trainer",
    "Гребной тренажёр (минуты)": "rowing-stationary",
    "Скакалка (минуты)": "rope-jumping",
    "Бег (минуты)": "running-treadmill",
    "Ходьба (минуты)": "walking-treadmill",
    "Жим в тренажёре Смита лёжа": "smith-machine-bench-press",
    "Становая тяга сумо": "sumo-deadlift",
    "Австралийские подтягивания": "inverted-row",
    "Тяга штанги обратным хватом": "reverse-grip-bent-over-rows",
    "Супермен": "superman",
    "Приседания в тренажёре Смита": "smith-machine-squat",
    "Отведение ноги назад в кроссовере": "one-legged-cable-kickback",
    "Тяга штанги к подбородку": "upright-barbell-row",
    "Жим в тренажёре на плечи": "machine-shoulder-military-press",
    "Молотковые сгибания на блоке (канат)": "cable-hammer-curls---rope-attachment",
    "Разгибание рук с гантелью в наклоне": "tricep-dumbbell-kickback",
    "Разгибание рук над головой на блоке": "cable-rope-overhead-triceps-extension",
    "Обратные скручивания": "reverse-crunch",
    "Мёртвый жук": "dead-bug",
    "Ролик для пресса": "ab-roller",
    "Степпер (минуты)": "stairmaster",
    "Мах гирей одной рукой": "one-arm-kettlebell-swings",
    "Гоблет-присед с гирей": "goblet-squat",
    "Жим гири стоя": "alternating-kettlebell-press",
    "Тяга гири в наклоне": "one-arm-kettlebell-row",
    "Турецкий подъём": "kettlebell-turkish-get-up-squat-style",
    "Прогулка фермера с гирей (секунды)": "farmers-walk",
    "Рывок гири": "one-arm-kettlebell-snatch",
    "Румынская тяга на одной ноге": "kettlebell-one-legged-deadlift",
    "Приседания с прыжком": "freehand-jump-squat",
    "Джампинг-джек (секунды)": "star-jump",
    "Тяга верхнего блока узким хватом": "close-grip-front-lat-pulldown",
    "Подъём гантелей перед собой": "front-dumbbell-raise",
    "Боковая планка (секунды)": "side-bridge",
    "Велосипед (пресс)": "air-bike",
    "Сведение рук в тренажёре «бабочка»": "butterfly",
    "Сгибание запястий": "palms-up-dumbbell-wrist-curl-over-a-bench",
    "Разведение ног в тренажёре": "thigh-abductor",
}
